### ISSUE TITLE
[ERROR] Entity to Dto Converting 도중 EntityNotFoundException 예외 Throw

### ISSUE THREAD

**Issue by key-del-jeeinho** [Promotion-official/among-api#1]
### Http Request
```http
POST http://localhost:8081/account/get-account?authorize_key=asda
Content-Type: application/json

{
  "email" : "grassintheglass@gmail.com"
}
```
### feature/request_authorize 오류처리 및 이슈를 위한 중간커밋 & 아래 Gist Link 참조
- https://gist.github.com/508cf1898558607522af76da97b72e3d (AuthorizeKeyIntercepter line : 17)
- https://gist.github.com/key-del-jeeinho/9a379e4d797d800b82aefb2055c5d700 (AuthorizeKeyService line : 37)
- https://gist.github.com/key-del-jeeinho/046ff2f138d6bb958b6e92fed2aef5d7 (AuthorizeKeyConverter line : 19)

### Error Log
```java
javax.persistence.EntityNotFoundException: Unable to find com.promotion.amongapi.domain.entity.AuthorizeKey with id asda
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$JpaEntityNotFoundDelegate.handleEntityNotFound(EntityManagerFactoryBuilderImpl.java:163)
	at org.hibernate.proxy.AbstractLazyInitializer.checkTargetState(AbstractLazyInitializer.java:286)
	at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:181)
	at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:310)
	at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45)
	at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)
	at com.promotion.amongapi.domain.entity.AuthorizeKey$HibernateProxy$uwdtOQ5f.getPermission(Unknown Source)
	at com.promotion.amongapi.domain.converter.AuthorizeKeyConverter.convertEntityToDto(AuthorizeKeyConverter.java:19)
	at com.promotion.amongapi.service.AuthorizeKeyService.count(AuthorizeKeyService.java:37)
	at com.promotion.amongapi.service.AuthorizeKeyService$$FastClassBySpringCGLIB$$7dc3b9ae.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692)
	at com.promotion.amongapi.service.AuthorizeKeyService$$EnhancerBySpringCGLIB$$5acb7a40.count(<generated>)
	at com.promotion.amongapi.intercepter.AuthorizeKeyInterceptor.preHandle(AuthorizeKeyInterceptor.java:17)
	at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:148)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1058)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:103)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:710)
	at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:459)
	at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:384)
	at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:312)
	at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:398)
	at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:257)
	at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:352)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:177)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

**Comment by key-del-jeeinho** [comment]
# Interceptor 의 예외 핸들링 및 SSL Security 활성화문제 해결
 Interceptor 레벨에서의 Exception 은 ExceptionHandler 을 쓸 수 없고, try / catch 문을 사용해 직접 예외 핸들링을 해주어야한다.
이에, Interceptor 단에서 EntityNotFoundException 이 throwing 될 경우, `response.setStatus()` 와 `response.getWriter().write()` 메서드를 통하여 response 객체를 설정해주고 Interceptor 의 preHandle 단에서 false 를 반환하게 하였다.

또한, 해당 오류로그의 한참 후에 SSL관련 예외가 throwing 되었다.
이를 고치기위해 구글링을 한 결과, application.property (.gitignore 된 파일) 의 DataSource 에서 SSL 사용여부를 false 로 해야한다는 사실을 알았고, DB url 의 끝부분에 `&useSSL=false` 를 추가하여 이를 해결하였다
